/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pumpcontrol;

import com.fazecast.jSerialComm.SerialPort;
import java.awt.print.PrinterException;
import java.text.NumberFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Gu_Lab_public
 */
public class GUI extends javax.swing.JFrame {
    
    //values for the fileds
    private int amount = 0;

    //fileds for data entry
    private NumberFormat amountFormat;

    //define the pump
    private static Pump the_pump;

    /**
     * Creates new form GUI
     */
    public GUI() {

        initComponents();
        
        setPump();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountFormat = NumberFormat.getNumberInstance();
        jFormattedTextField_volume = new javax.swing.JFormattedTextField(amountFormat);
        jLabel_volume_chemical = new javax.swing.JLabel();
        jButton_start = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_output = new javax.swing.JTextArea();
        jLabel_output = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFormattedTextField_volume.setValue(new Integer(amount));
        jFormattedTextField_volume.setPreferredSize(new java.awt.Dimension(60, 30));
        amountFormat = NumberFormat.getNumberInstance();
        jFormattedTextField_volume.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jFormattedTextField_volumePropertyChange(evt);
            }
        });

        jLabel_volume_chemical.setText("volume of chemical to add (numbers only in uL)");

        jButton_start.setText("Start");
        jButton_start.setPreferredSize(new java.awt.Dimension(100, 100));
        jButton_start.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_startMouseClicked(evt);
            }
        });

        jTextArea_output.setEditable(false);
        jTextArea_output.setColumns(20);
        jTextArea_output.setRows(5);
        jScrollPane1.setViewportView(jTextArea_output);

        jLabel_output.setText("Output");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_output)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFormattedTextField_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_volume_chemical)
                        .addGap(8, 8, 8)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_volume_chemical))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_output)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void setPump(){
                        // Gets all available ports
        SerialPort[] ports = SerialPort.getCommPorts();

        // Displays all available ports for the use to use
        ArrayList portsNames = new ArrayList(ports.length);
        for (int i = 0; i < ports.length; i++) {            
            System.out.println("port " + i + ": " + ports[i].getSystemPortName());
            portsNames.add(ports[i].getSystemPortName());
        }

        // Instantiate the pump connection with PC
        // Asks the user for input for which port to use
        System.out.println("Please select the port for the pump");
        try (Scanner input = new Scanner(System.in)) {
            String userport = input.next();
            
            // make sure user select the correct port name
            while (!portsNames.contains(userport)) {
                System.out.println("Invalid input, please select the port for the pump: ");
                userport = input.next();
            }
            int numOfPort = portsNames.indexOf(userport);
            the_pump = new Pump(ports[numOfPort]);
        }
    }
    
    private void jButton_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_startMouseClicked
        try {
            // TODO add your handling code here:            
            runForOneCycle(amount);
        } catch (InterruptedException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_startMouseClicked

    private void jFormattedTextField_volumePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jFormattedTextField_volumePropertyChange
        // TODO add your handling code here:
        Object source = evt.getSource();
        if (source == jFormattedTextField_volume) {
            try{
            amount = Integer.parseInt(jFormattedTextField_volume.getText());
            } catch (NumberFormatException e){
                System.out.println("Must enter an integer");
            }
        }
    }//GEN-LAST:event_jFormattedTextField_volumePropertyChange

    public void runForOneCycle(int volume) throws InterruptedException {
        //get start
        the_pump.flipToWaster();
        Thread.sleep(1000);
        the_pump.intialize();
        jTextArea_output.append("Initialized");
        
        Thread.sleep(10000);

        the_pump.setMaxSpeed(10000);
        Thread.sleep(500);

        int[] parameters = calPumpCycAndVol(volume);
        for (int i = 0; i < parameters[0]; i++) {
            the_pump.flipToSolution();
            Thread.sleep(500);
            the_pump.setPosition(48000);
            Thread.sleep(6000);
            the_pump.flipToWaster();
            Thread.sleep(500);
            the_pump.dispose(48000);
            Thread.sleep(6000);
        }
        if (parameters[1] > 0) {
            the_pump.flipToSolution();
            Thread.sleep(500);
            the_pump.setPosition(parameters[1] * 48000 / 250);
            Thread.sleep(6000);
            the_pump.flipToWaster();
            Thread.sleep(500);
            the_pump.dispose(parameters[1] * 48000 / 250);
            Thread.sleep(6000);
        }
    }

    private int[] calPumpCycAndVol(int volume) {
        int[] result = new int[2];
        int numCyc = volume / the_pump.maxVol;
        int remainder = volume % the_pump.maxVol;
        result[0] = numCyc;
        result[1] = remainder;
        return result;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_start;
    private javax.swing.JFormattedTextField jFormattedTextField_volume;
    private javax.swing.JLabel jLabel_output;
    private javax.swing.JLabel jLabel_volume_chemical;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_output;
    // End of variables declaration//GEN-END:variables
}
